### ISSUE TITLE
Item pipes can cause intense lag spikes for modest setups that remain after removing most mods

### ISSUE THREAD

**Issue by truepurpledino** [AztechMC/Modern-Industrialization#1173]
This has been discussed in [discord](https://discord.com/channels/754461970870173767/760125612126896196/1409325570365587466), but I have noticed that very modest single pipe network for a base that moves about 500 items every 3 second cycle creates immense TPS lag spikes, which would usually only happen with really bad interactions between other mod's inventories and MI item pipes on empty blacklist in fabric. I am using EI and MI tweaks and the likes, but after some tinkering (trying connecting item pipes to chained barrels/machines, OR trying to connect only MI machines and barrels individually, all on empty blacklist), I could not make any significant impact on reducing the amplitude of the lag spikes caused by the MI item pipes. As a simple comparison, I loaded up a MI base I made in the Fabric version of Statech Industry and one on the Neoforge 1.21.1 version of Statech Industry I am developing. Simply looking at the TPS graph, you can see the lag when comparing a Neoforge pipe that moves 500 items and a Fabric pipe that moves 2500.

<img width="1457" height="797" alt="Image" src="https://github.com/user-attachments/assets/3b024e8f-8ca0-4d2a-9749-5f8e980da27f" />

As for spark profiling, for a minute period, I found that spark the profiler shows on neoforge that moving 500 items, pipes.item.ItemNetwork.tick() takes 2092 ms whilst on fabric, moving about 2000 items, pipes.item.ItemNetwork.tick() takes 28 ms.
Here are spark profiles: [Neoforge, moving 500 items](https://spark.lucko.me/RB5L5iSpaX), [Fabric, moving 2000 items](https://spark.lucko.me/jHeEFl0tfV).

**Comment by Technici4n** [comment]
There is a mod called azurelib that is making stack creation significantly slower...

**Comment by truepurpledino** [comment]
I have disabled azurelib and performance seems pretty much identical. Spark profile: https://spark.lucko.me/uoWwaIfAdr

<img width="750" height="623" alt="Image" src="https://github.com/user-attachments/assets/2fcefa82-6604-4514-bf9d-c8ab21b4cc3b" />

**Comment by Technici4n** [comment]
Hmmm indeed, ItemStack creation is still quite slow. There's not much I can do here. NeoForge for MC 1.21.9+ should fix this with the new transfer API. Note that item pipes are only 3.5% of the profiles you sent

**Comment by truepurpledino** [comment]
They are 3,5%, but it's how they spike that causes issues with gameplay, the machines ticking taking more time are comparitively a lot less worse for gameplay. Is there any way to profile or debug for tick spikes specifically?

**Comment by Natanaelel** [comment]
`/spark profiler start --only-ticks-over <milliseconds>`
https://spark.lucko.me/docs/Command-Usage

**Comment by truepurpledino** [comment]
Here are spark reports for with `--only-ticks-over 60`:
Using chainers from EI: https://spark.lucko.me/0e6acqYEgO
Not using chainers from EI: https://spark.lucko.me/NKvZApIeO2

**Comment by James103** [comment]
A workaround I found is to whitelist, in the item pipe connections, the items you want to input or output for each and every connection. For example, an I/O pipe connection to an assembler slot-locked into making only Bronze Drills should whitelist Bronze Drill Head, Iron Gear, Item Pipe, and Fluid Pipe, instead of an empty blacklist. An empty blacklist will still work, but is much less performant compared to a properly-set whitelist.

**Comment by Technici4n** [comment]
Fixed by https://github.com/AztechMC/Modern-Industrialization/pull/1179.

**Comment by truepurpledino** [comment]
I'd like to reopen this issue because this seems to be a bug that has also happened in ATM10 (see these [messages](https://discord.com/channels/754461970870173767/760125612126896196/1449281525987414087)), but never in Craftoria, and still happens after #1179 in my newest updated run of StaTech 1.21.1:

I've done a mod difference between Craftoria, [StaTech 1.21.1](github.com/truepurpledino/StaTech-Industry-1.21.1-Unofficial) and ATM10 where the bug happens on the two latter and not in Craftoria. 8 mods (listed below) were identified and disabled for a new playthrough seeing as it the bug seems to happen and persist after disabling most mods (down to 21 mods or so, from testing from the last time this happened, in september 2025).

Here are some spark reports from the new run, where my single pipeline isn't moving more than 300 items per cycle:
03/01/2026 (less infra): https://spark.lucko.me/lxrQlz4Hbs 
04/01/2026 (more infra):  https://spark.lucko.me/HivO0ZzEyv
Picture of spikes on january 4:
<img width="814" height="252" alt="Image" src="https://github.com/user-attachments/assets/3412e037-06b0-42e3-b81c-e2c4749c7793" />

04/01/2026, later: https://spark.lucko.me/qmpW0Irco3
05/01/2026 mv: https://spark.lucko.me/tgjcq0PH7e

from today, when I recognised peaks in the TPS graph:
https://spark.lucko.me/bO1q4BRdBd, only-ticks-over 20
https://spark.lucko.me/Xyl3yN5FlV, only-ticks-over 10
Picture of spikes seen today:
<img width="765" height="256" alt="Image" src="https://github.com/user-attachments/assets/10f6d75b-60d2-4e67-bd29-8931c79d78e0" />

These spark reports also seem to show some other performance issues

Mods that were present in ATM10 and StaTech 1.21.1 but NOT in Craftoria, that I've disabled in my new playthrough:

- connectivity-1.21.1-7.2.jar
- createaddition-1.5.8.jar
- drippyloadingscreen_neoforge_3.0.12_MC_1.21.1.jar
- ExplorersCompass-1.21.1-3.0.3-neoforge.jar
- getittogetherdrops-neoforge-1.21.5-1.4.jar
- NoChatReports-NEOFORGE-1.21.1-v2.9.1.jar
- polyeng-0.4.1.jar (polymorphic energistics)
- polymorph-neoforge-1.1.0+1.21.1.jar
- solcarrot-1.21.1-1.16.5.jar
- ToastControl-1.21.1-9.0.1.jar

Mods that are present in Statech 1.21.1 and NOT in Craftoria nor ATM10:

- [Advancement Plaques](https://www.curseforge.com/projects/499826) (AdvancementPlaques\-1\.21\.1\-neoforge\-1\.6\.8\.jar)
- [Almanac](https://www.curseforge.com/projects/1115285) (Almanac\-1\.21\.1\-2\-neoforge\-1\.5\.0\.jar\.disabled)
- [Angel Ring 3](https://www.curseforge.com/projects/333396) (angelring\-1\.21\.1\-neoforge\-3\.0\.0\+beta\.3\.jar)
- [Architects Palette](https://www.curseforge.com/projects/433862) (architects\_palette\-neoforge\-1\.21\.1\-1\.4\.0\-beta\.5\.jar)
- [Biolith](https://www.curseforge.com/projects/852512) (biolith\-neoforge\-3\.0\.10\.jar)
- [Chimes](https://www.curseforge.com/projects/350464) (Chimes\-v2\.0\.3\-1\.21\.1\-NeoForge\.jar)
- [Chunky](https://www.curseforge.com/projects/485681) (Chunky\-NeoForge\-1\.4\.23\.jar)
- [Clean Tooltips](https://www.curseforge.com/projects/855017) (clean\_tooltips\-1\.1\-neoforge\-1\.21\.1\.jar)
- [CleanView](https://www.curseforge.com/projects/226889) (cleanview\-1\.21\.1\-v1\-neoforge\.jar)
- [Clickable Advancements mod](https://www.curseforge.com/projects/511733) (clickadv\-1\.21\-3\.8\.jar)
- [Cognition](https://www.curseforge.com/projects/579484) (Cognition\-v2\.4\.9\-1\.21\.1\.jar)
- [CoroUtil](https://www.curseforge.com/projects/237749) (coroutil\-neoforge\-1\.21\.0\-1\.3\.8\.jar)
- [Create Crafts & Additions](https://www.curseforge.com/projects/439890) (createaddition\-1\.5\.9\.jar\.disabled)
- [Create Let The Adventure Begin](https://www.curseforge.com/projects/1007872) (create\_ltab\-3\.4\.3\.jar)
- [Create: Easy Structures](https://www.curseforge.com/projects/949158) (create\_easy\_structures\-0\.2a\-neoforge\-1\.21\.1\.jar)
- [Create: Rustic Structures](https://www.curseforge.com/projects/1232975) (create\_rustic\_structures\-1\.0\.0\-neoforge\-1\.21\.1\.jar)
- [Create: Structures Arise](https://www.curseforge.com/projects/1010066) (create\_structures\_arise\-167\.40\.39 Release\-neoforge\-1\.21\.1\.jar)
- [Create: Vibrant Vaults](https://www.curseforge.com/projects/1251719) (create\_vibrant\_vaults\-0\.3\.2\.jar)
- [Create](https://www.curseforge.com/projects/328085) (create\-1\.21\.1\-6\.0\.8\.jar)
- [Custom Ore Veins](https://www.curseforge.com/projects/949185) (customoreveins\-neoforge\-1\.0\.1\.jar)
- [Databank](https://www.curseforge.com/projects/1181408) (databank\-1\.3\.0\.jar)
- [Decorative Blocks Reborn](https://www.curseforge.com/projects/1327768) (DecorativeBlocks\-Reborn\-neoforge\-1\.21\.1\-6\.0\.1\.jar)
- [Drippy Loading Screen](https://www.curseforge.com/projects/511770) (drippyloadingscreen\_neoforge\_3\.1\.0\_MC\_1\.21\.1\.jar\.disabled)
- [EMI Loot](https://www.curseforge.com/projects/681783) (emi\_loot\-0\.7\.8\+1\.21\+neoforge\.jar)
- [Expanded Delight](https://www.curseforge.com/projects/620770) (expandeddelight\-0\.1\.3\.2\.jar)
- [Fallingleaves](https://www.curseforge.com/projects/463155) (fallingleaves\-1\.21\.1\-2\.5\.1\.jar)
- [Faster Ladder Climbing](https://www.curseforge.com/projects/258881) (fasterladderclimbing\-0\.2\.14\.jar)
- [Flight API](https://www.curseforge.com/projects/1219748) (flightapi\-neoforge\-1\.1\.1\.jar)
- [Forgiving Void](https://www.curseforge.com/projects/271009) (forgivingvoid\-neoforge\-1\.21\.1\-21\.1\.5\.jar)
- [FPS Reducer](https://www.curseforge.com/projects/280294) (FpsReducer2\-neoforge\-1\.21\-2\.10\.jar)
- [Free Look](https://www.curseforge.com/projects/969891) (free\_look\_neoforge 1\.21\.0 \- 1\.21\.6 V11\.jar)
- [Guard Villagers](https://www.curseforge.com/projects/360203) (guardvillagers\-2\.4\.5\-1\.21\.1\.jar)
- [Hang Glider](https://www.curseforge.com/projects/852668) (HangGlider\-v21\.1\.0\-1\.21\.1\-NeoForge\.jar)
- [HaydenAPI](https://www.curseforge.com/projects/1219737) (haydenapi\-neoforge\-1\.0\.4\.jar)
- [Inventory Essentials](https://www.curseforge.com/projects/368825) (inventoryessentials\-neoforge\-1\.21\.1\-21\.1\.12\.jar)
- [Inventory HUD\+](https://www.curseforge.com/projects/357540) (inventoryhud\.neoforged\.1\.21\.1\-3\.4\.28\.jar)
- [Just Enough Effects Descriptions](https://www.curseforge.com/projects/532286) (jeed\-1\.21\-2\.3\.1\.jar)
- [Let Me Despawn](https://www.curseforge.com/projects/663477) (letmedespawn\-1\.21\.x\-neoforge\-1\.5\.0\.jar\.disabled)
- [LibX](https://www.curseforge.com/projects/412525) (LibX\-1\.21\.1\-6\.0\.6\.jar)
- [Log Begone](https://www.curseforge.com/projects/623560) (logbegone\-neoforge\-1\.21\.1\-1\.0\.3\.jar)
- [Luki's Ancient Cities](https://www.curseforge.com/projects/1190728) (lukis\-ancient\-cities\-v1\.2\.jar)
- [Luki's Grand Capitals](https://www.curseforge.com/projects/1003666) (lukis\-grand\-capitals\-1\.1\.2\.jar)
- [Mixed Litter](https://www.curseforge.com/projects/1221222) (mixed\_litter\-1\.0\.3\.jar)
- [Moderately Enough Effect Descriptions](https://www.curseforge.com/projects/918638) (MEED\-1\.21\.1\-7\.5\.jar)
- [Modpack Update Checker](https://www.curseforge.com/projects/847414) (modpack\-update\-checker\-1\.21\.1\-neoforge\-0\.15\.6\.jar)
- [MoreJS](https://www.curseforge.com/projects/666198) (morejs\-neoforge\-1\.21\.1\-0\.16\.0\.jar)
- [No Man's Land](https://www.curseforge.com/projects/538493) (nomansland\-1\.4\.5\.jar)
- [Paperdoll](https://www.curseforge.com/projects/537079) (paperdoll\-neoforge\-1\.3\.1\-mc1\.21\.jar)
- [Pastel](https://www.curseforge.com/projects/1264556) (Pastel\-1\.1\.4\.1\.jar)
- [Paxi](https://www.curseforge.com/projects/1015157) (Paxi\-1\.21\.1\-NeoForge\-5\.1\.3\.jar)
- [Puzzles Lib](https://www.curseforge.com/projects/495476) (PuzzlesLib\-v21\.1\.39\-1\.21\.1\-NeoForge\.jar)
- [Raise Sound Limit Simplified](https://www.curseforge.com/projects/646146) (rsls\-neoforge\-1\.1\.10\.jar)
- [Raised](https://www.curseforge.com/projects/570368) (raised\-neoforge\-1\.21\.1\-5\.0\.2\.jar)
- [Responsive Shields](https://www.curseforge.com/projects/557556) (responsiveshields\-2\.4\-neoforge\-mc1\.21\.x\.jar)
- [Right Click Harvest](https://www.curseforge.com/projects/452834) (rightclickharvest\-neoforge\-4\.6\.0\+1\.21\.1\.jar)
- [ShulkerBoxTooltip](https://www.curseforge.com/projects/315811) (shulkerboxtooltip\-neoforge\-5\.1\.8\+1\.21\.1\.jar)
- [Simple Inventory Sorter](https://www.curseforge.com/projects/240633) (inventorysorter\-1\.21\.1\-24\.0\.24\.jar)
- [Smoothchunk mod](https://www.curseforge.com/projects/582327) (smoothchunk\-1\.21\-4\.1\.jar)
- [Stellar View](https://www.curseforge.com/projects/865273) (Stellar View\-1\.21\.1\-0\.5\.2\-NeoForge\.jar)
- [Structure Layout Optimizer](https://www.curseforge.com/projects/1087831) (structure\_layout\_optimizer\-neoforge\-1\.0\.11\.jar)
- [Structurify](https://www.curseforge.com/projects/1087551) (structurify\-neoforge\-2\.0\.8b\+mc1\.21\.1\.jar)
- [Tips](https://www.curseforge.com/projects/306549) (tipsmod\-neoforge\-1\.21\.1\-21\.1\.3\.jar)
- [TipTheScales](https://www.curseforge.com/projects/282313) (TipTheScales\-neoforge\-1\.21\.1\-16\.0\.0\.1\.jar)
- [Travel Anchors](https://www.curseforge.com/projects/1208628) (travelanchors\-1\.1\.1\.jar)
- [UsefulSlime](https://www.curseforge.com/projects/417702) (UsefulSlime\-neoforge\-1\.21\-1\.12\.1\.jar)
- [What Are They Up To](https://www.curseforge.com/projects/945479) (watut\-neoforge\-1\.21\.0\-1\.2\.7\.jar)

Picture of the very modest base+[observable](https://observable.tas.sh/p/q1Z7H)
<img width="2560" height="1387" alt="Image" src="https://github.com/user-attachments/assets/27efc04a-d1af-4608-b48a-88687088db58" />

**Comment by James103** [comment]
Do you have every or almost every item pipe connection on an empty blacklist?

**Comment by truepurpledino** [comment]
every pipe except those connected to Create Depots are on empty blacklist into slot locked machines or chainers chaining slot locked machines (which from my testing in the last world that had this bug, have no difference between the two)

**Comment by James103** [comment]
For anyone else still running into this issue, do you have any EI machine chainers or other non-MI blocks connected to any of your item pipe networks? If so, please set those connections to whitelist with the items you intend the block to receive or send into the network. As far as I understand, MI pipes connected to slot-locked MI machines automatically optimize an empty blacklist to a whitelist taken from the slot filters to improve performance; this does not work for EI machine chainers and other non-MI blocks.

**Comment by Swedz** [comment]
As of Swedz/Extended-Industrialization#305 (version [1.15.30](https://github.com/Swedz/Extended-Industrialization/releases/tag/1.15.30-1.21.1)) the chainer gets the same benefit.

To clarify, it was only the chainer that lacked this benefit. All other EI machines get this by nature of using `MIInventory`.
